# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    error_controller: App\Controller\ErrorController::error
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    session: true

when@test:
    framework:
        error_controller: App\Controller\ErrorController::error
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
